# Dependabot configuration for Vintage Store multi-module project
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Root pom.xml - Parent POM management
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "aoncal"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"

  # Infrastructure module - Docker and shared configuration
  - package-ecosystem: "maven"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(infrastructure)"
      include: "scope"
    labels:
      - "dependencies"
      - "infrastructure"
      - "maven"

  # RAG module - Document ingestion and vector database
  - package-ecosystem: "maven"
    directory: "/rag"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(rag)"
      include: "scope"
    labels:
      - "dependencies"
      - "rag"
      - "ai"
      - "maven"

  # Web application with standalone LangChain4j
  - package-ecosystem: "maven"
    directory: "/web-langchain4j"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(web-langchain4j)"
      include: "scope"
    labels:
      - "dependencies"
      - "web-langchain4j"
      - "quarkus"
      - "ai"
      - "maven"

  # Web application with Quarkus LangChain4j extension
  - package-ecosystem: "maven"
    directory: "/web-quarkus"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(web-quarkus)"
      include: "scope"
    labels:
      - "dependencies"
      - "web-quarkus"
      - "quarkus"
      - "ai"
      - "maven"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "agoncal"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
