# To visualise the content of a Redis instance, you can use the Redis Commander tool.
# npm install -g redis-commander
# redis-commander
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:8.0.3-alpine

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8089:8081"

